### PR TITLE
cleanup zig.mod

### PR DESCRIPTION
**Pull request by nektro**
seeing how this affects windows actions

### CODE REVIEW

**Comment by yrashk** [comment]
Interestingly enough, I tried to use a Debug build for a CI job (#11) and the error is still the same:

```
Run .\zigmod ci
  .\zigmod ci
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
thread 2532 panic: attempt to use null value
Unable to dump stack trace: FileNotFound
```

Maybe I missing something, or maybe I need to make a build on Windows (this one has been cross-compiled)

**Comment by nektro** [comment]
do you happen to have access to a windows machine to try running this locally?

**Comment by yrashk** [comment]
I do and it works fine. I have, however, noticed that sometimes I get the
same panic on macos when I run `zigmod ci` (but not fetch)

**Comment by nektro** [comment]
hmm that is a nice observation because https://github.com/Hejsil/zig-bench does not have a `zigmod.lock`

**Comment by nektro** [comment]
fixed it

the `.gitattributes` file was missing and windows files have `\r` in them by default after a `git clone`

**Comment by yrashk** [comment]
Thank you! I used this in 0568dad1c19abc40fed12c7628187c882b22b3ab and it looks like it fixed it indeed!

**Pull request closed without merging**
